# Generated by Django 5.2.14 on 2026-05-26 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='subject_code',
            field=models.CharField(default='UNKNOWN', max_length=20),
        ),
    ]
