# Generated by Django 5.2.14 on 2026-06-10 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk_api', '0003_exam_examiner'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
